[package]
name = "aranea"
version = "0.0.0"
authors = ["u7f8au7fbd <u7f8au7fbd@outlook.com>"]
edition = "2021"

[dependencies]
#基本
tokio = { version = "*", features = ["full"] }
rand = { version = "*" }
chrono = { version = "*" }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
#GUI
eframe = { version = "*" }
egui = { version = "*" }
egui_extras = { version = "*" }
catppuccin-egui = { version = "*", default-features = false, features = [
    "egui28",
] }
#スクレイピング
reqwest = { version = "*" }
select = { version = "*" }
scraper = { version = "*" }
spider = { version = "*" }
#機械学習
ndarray = { version = "0.15.6" }
linfa = { version = "*" }
linfa-bayes = { version = "*" }
linfa-clustering = { version = "*" }
linfa-datasets = { version = "*" }
linfa-elasticnet = { version = "*" }
linfa-ftrl = { version = "*" }
linfa-hierarchical = { version = "*" }
linfa-ica = { version = "*" }
linfa-kernel = { version = "*" }
linfa-linear = { version = "*" }
linfa-logistic = { version = "*" }
linfa-nn = { version = "*" }
linfa-pls = { version = "*" }
linfa-preprocessing = { version = "*" }
linfa-reduction = { version = "*" }
linfa-svm = { version = "*" }
linfa-trees = { version = "*" }
linfa-tsne = { version = "*" }
#グラフ
charming = { version = "*" }
plotters = { version = "*" }
#形態素解析q
lindera = { version = "*", features = ["filter", "unidic"] }


[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
[profile.release.package."*"]
opt-level = 3
